name: Deploy ELK Stack on EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'  # Ensure compatibility with your EKS cluster

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name <your-cluster-name> --region us-west-2

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.0  # Specify the version of Helm to use

    - name: Ensure Helm repository configuration directory exists
      run: mkdir -p /home/runner/.config/helm/repositories

    - name: Add Elastic Helm repo
      run: helm repo add elastic https://helm.elastic.co

    - name: Update Helm repositories
      run: helm repo update

    - name: Deploy Elasticsearch
      run: |
        helm upgrade --install elasticsearch elastic/elasticsearch \
        --namespace logging --create-namespace

    - name: Deploy Kibana
      run: |
        helm upgrade --install kibana elastic/kibana \
        --namespace logging

    - name: Deploy Logstash
      run: |
        helm upgrade --install logstash elastic/logstash \
        --namespace logging
